spring:
  datasource:
    url: jdbc:postgresql://cloud_database:5432/cloud_database
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  flyway:
    enabled: true

client:
  port:
    value: ${CLIENT_PORT:4200}

email:
  config:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}